# Optional config file for the theme.

# Variables that are in this file, can be used in your twig template like {{ theme.foo }}
# Note: If variables do not immediately show up, clear the cache, in the Bolt Backend.

# Template filenames: 
maintenance_template: maintenance.twig
homepage_template: index.twig
record_template: record.twig
listing_template: listing.twig
search_results_template: listing.twig
