# This file defines the menus on the website. See the documentation for
# details: http://docs.bolt.cm/menus

main:
  - label: Home
    title: This is the first menu item.
    path: /
    class: first
  - label: The Work
    path: /work
  - label: The Latest
    path: /latest/
  - label: The Thoughts
    path: /thoughts/
  - label: The Bears
    path: /bears/
  - label: Get In Touch
    path: /contact/
    class: button
